### ISSUE TITLE
Feature: User can view a random recipe

### ISSUE THREAD

**Issue by Cole-Allen** [Cole-Allen/AJAX-MealDB-Website#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a random recipe from MealDB

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Refreshing the website will generate a new recipe

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![mealdb](https://user-images.githubusercontent.com/56735362/135324324-e5a060fc-d3f6-4758-92a6-10d51844a993.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create an HTML skeleton
- [x] Create a CSS stylesheet
- [x] Create a main JavaScript file
- [x] Add basic layout classes and rulesets
- [x] Use a placeholder recipe for testing
- [x] Implement mealDB's random API
- [x] replace the placeholder recipe with the random recipe
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
