### ISSUE TITLE
Feature: User can add a recipe to their favorites and view them

### ISSUE THREAD

**Issue by Cole-Allen** [Cole-Allen/AJAX-MealDB-Website#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add a recipe to their favorites and view them later

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking the heart next to the recipe name, will add a recipe to the user's favorites. Clicking on the favorites tab will show all their previously favorited recipes

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/56735362/135329248-f7413706-1bf0-4be8-a1a1-1f842f2e0259.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a data variable in JavaScript
- [x] Add functionality to the heart element of the recipe
- [x] Add functionality to the tabs on top
- [x] Add the current recipe to an array
- [x] Store the data element in local Storage before unload
- [x] retrieve data from local storage after refreshing
- [x] ...
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
