### ISSUE TITLE
Feature: User can search for a recipe by name

### ISSUE THREAD

**Issue by Cole-Allen** [Cole-Allen/AJAX-MealDB-Website#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can go to the 'Name' tab to try searching for a recipe by name

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking on the 'Name' tab will take the user to a search bar where they can try and search for a recipe by name
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/56735362/135330984-4c670e46-87f4-4e25-8070-940ac29c8d39.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a 'view' for the 'name' tab
- [x] Add a form with a text input
- [x] Add a button to send the form
- [x] Check API for name
- [x] Show recipe if found
- [x] If recipe is not found or unavailable, show a message saying so
    - [x] Allow user to try again
- [ ] ...
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
