### ISSUE TITLE
Feature: User can check Categories

### ISSUE THREAD

**Issue by Cole-Allen** [Cole-Allen/AJAX-MealDB-Website#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can check the categories tab to see a list of categories

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can go to the categories tab to view a list of categories, after clicking on  a category, it will show all the recipes in that category

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/56735362/135335786-6bf3aa09-4c52-4bad-af76-09b5c0962744.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Get list of categories from API
- [ ] Display the categories as a list
- [ ] After clicking a category, display all the recipes found
- [ ] after clicking on a recipe, display recipe
- [ ] ...
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
